### ISSUE TITLE
Unsupported major.minor version 51.0 when downgrading to 1.6

### ISSUE THREAD

**Issue by montecillodavid** [RestExpress/RestExpress-Archetype#2]
when changing my jre and jdk to 1.6 because the server in which i upload the restexpress have 1.6 version of openjdk, error is org/restexpress/serialization/SerializationProvider : Unsupported major.minor version 51.0. 

Is it possible if I downgrade the jre to 1.6 and let it be compatible with the server which is openjdk 1.6 and not breaking the code?

**Comment by tfredrich** [comment]
Unless this is causing a production issue, I'd recommend upgrading to at least JDK 1.7. Let me know otherwise.
